version: '3.8'

services:
  reverse_proxy:
    build: ./TP1_Devops/TP_HTTP
    ports:
      - "8070:80"
    networks:
      - app-network
    container_name: reverse_proxy
    depends_on:
      - simple-api-students

  simple-api-students:
    build: ./TP1_Devops/TP_JAVA/simple-api-student-main
    ports:
      - "8080:8080"
    networks:
      - app-network
    container_name: simple-api-students
    depends_on:
      - bdd_postgresql

  bdd_postgresql:
    build: ./TP1_Devops/TP_Docker
    ports:
      - "8888:5432"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=usr
      - POSTGRES_PASSWORD=pwd
    volumes:
      - /home/hamza/Test:/var/lib/postgresql/data
    networks:
      - app-network
    container_name: bdd_postgresql


networks:
  app-network:

